The `DDD-unit-test/DDD-unit-test.csproj` file exists in the repository. Ensure the `working-directory` is correctly set to the repository root or to the correct path where the project resides.

Here is a revised version of your workflow file:

```yaml
name: DDD report program Unit Test

on:
  push:
    branches: 
    - master
  
jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Setup .NET environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Dependencies Restore 
      run: dotnet restore
      working-directory: DDD-unit-test

    - name: Project Build
      run: dotnet build
      working-directory: DDD-unit-test
      
    - name: Run Test
      run: dotnet test --no-build --verbosity normal
      working-directory: DDD-unit-test
