name: DDD report program Unit Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install Test Platform
        working-directory: DDD report program/DDD report program
        run: dotnet add package Microsoft.TestPlatform --version 17.6.0

      - name: Dependencies Restore
        working-directory: DDD report program/DDD report program
        run: dotnet restore

      - name: Project Build
        working-directory: DDD report program/DDD report program
        run: dotnet build

      - name: Project Test
        working-directory: DDD report program/DDD report program
        run: dotnet test
